----------------------------------------------------------------------------------------------------
--- INITIAL SETUP DATABASE FOR PLUGIN USERS
----------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS DATA.USERS(NAME VARCHAR(64), PASSWORD VARCHAR(64), GROUPS VARCHAR(255), ROLES VARCHAR(255), FULL_NAME VARCHAR(255), EMAIL_ADDRESS VARCHAR(255));

INSERT INTO DATA.USERS VALUES ('admin', 'admin', 'admin', 'admin,user','Administrator','admin@example.com');

CREATE TABLE IF NOT EXISTS DATA.GROUPS(NAME VARCHAR(64));
INSERT INTO DATA.GROUPS VALUES ('ALL');
INSERT INTO DATA.GROUPS VALUES ('ADMIN');
INSERT INTO DATA.GROUPS VALUES ('USER');

CREATE TABLE IF NOT EXISTS DATA.ROLES(NAME VARCHAR(64));
INSERT INTO DATA.ROLES VALUES ('ADMIN');
INSERT INTO DATA.ROLES VALUES ('USER');
INSERT INTO DATA.ROLES VALUES ('EDITOR');
INSERT INTO DATA.ROLES VALUES ('EDITOR_IN_CHIEF');
INSERT INTO DATA.ROLES VALUES ('VISITOR');
