package org.drdevelopment.webtool.configuration;

public enum ConfigParam {
	DEVELOPMENT_MODE,
	DB_PASSWORD,
	DB_CIPHER_PASSWORD,
	DB_USERNAME,
	DB_PORT,
	DB_CONSOLE_PORT,
	DB_SQL_LOGGING,
	DB_SQL_LOGGING_THRESSHOLD_IN_MS,
	WEBSERVER_HTTP_PORT,
	WEBSERVER_HTTPS_PORT,
	WEBSERVER_KEYSTORE_FILENAME,
	
	IMAGE_PREVIEW_WIDTH,
	IMAGE_PREVIEW_HEIGHT,
	HEALTH_CHECK_INTERVAL_IN_SECONDS;

}
